### ISSUE TITLE
ValueError in datamodel.Data

### ISSUE THREAD

**Issue by anatolec** [AI-team-UoA/pyJedAI#16]
**Describe the bug**
Hey, great job for this package. Is it still being maintained ? I'd like to know before using it in prod.
Also, I believe there is a bug in `datamodel.Data`. If you pass a `dataset_2` that does not contain `id_column_name_1` (which seems like a valid case) you will get a `ValueError`.

**To Reproduce**
```
import pandas as pd
from pyjedai.datamodel import Data

df1 = pd.DataFrame({'id': [1, 2], 'data': ['a', 'b']})
df2 = pd.DataFrame({'other_id': [1, 2], 'data': ['a', 'b']})
Data(
    dataset_1=df1,
    id_column_name_1="id",
    dataset_2=df2,
    id_column_name_2="other_id",
)
```
--> ValueError

**Expected behavior**
No ValueError

**Additional context**
I believe [here](https://github.com/AI-team-UoA/pyJedAI/blob/6bd3b259faebf16c534a5af1b5dbe4a3db5e575d/src/pyjedai/datamodel.py#L152), it should be `self.attributes_2.remove(self.id_column_name_2)` instead of `self.attributes_2.remove(self.id_column_name_1)`

**Comment by Nikoletos-K** [comment]
Hello! Yes it is maintained and will be expanded even more. As for the bug, you're right. Thanks for your trace and detailed report. I fixed it and will be updated asap in the next release.

Feel free to contact me if you need anything else.

Cheers,
Konstantinos
