### ISSUE TITLE
Hello! Collaborate and cross-inspire?

### ISSUE THREAD

**Issue by NickCrews** [AI-team-UoA/pyJedAI#17]
Hi there! Nice to meet you. I'm a software engineer working on entity resolution. I've been reading a lot of your papers on the topic and have found them extremely helpful, so thank you for that.

I just found this repo, it looks quite useful (PS you might want to [add topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to this repo so it is easier to discover, I missed this repo until now because of this). I have been working on an entity resolution framework [called mismo](https://github.com/nickcrews/mismo) that looks quite similar. I am looking forward to reading this repo more and using it as inspiration for mismo. I invite you to take a look at mismo as well, and I hope that we can both learn things from each other and ask a lot of questions :)

Some things I hope to port to mismo:

- Many of the algorithms you have implemented.
- Pipeline mechanics
- Schema unification
- Plotting and evaluation methods

Some things you might find interesting in mismo

- I use [ibis](https://github.com/ibis-project/ibis) with duckdb, not pandas. This gives MUCH better performance and scalability than in-memory, greedily-evaluated pandas.
- Using altair for interactive, rich plots instead of matplotlib
- using reaction and solara for rich interactive jupyter widgets

Cheers,
Nick

**Comment by Nikoletos-K** [comment]
Hi Nick!

Thanks for your interest in pyJedAI and our research on Entity Resolution. If I understand correctly, we have Topics on our repo.  If you want to suggest any new one that would help this repo be more accessible, feel free. 

Our code is open-access. I suggest you to pip install and make the appropriate wrappers. That would be a handy approach. Any questions are welcome!

Indeed mismo looks interesting! We used pandas for easy-usability but as you said it lacks on efficiency many times. As for the plotting we use matplotlib and Plotly that also provides interactive plots. And finally for our demos we prefer building them in Google Colab as it offers widgets and really no-code notebooks.

Also it would be really nice to benchmark mismo over the 10 popular available datasets for ER. You can find them in [Zenodo](https://zenodo.org/records/7252010).

Cheers,
Konstantinos
