### ISSUE TITLE
'export_pairs' is not working due to missing 'write' function

### ISSUE THREAD

**Issue by Amselco** [AI-team-UoA/pyJedAI#22]
**Describe the bug**
'export_pairs' is not working due to missing 'write' function

**To Reproduce**

add w.export_pairs() to WorkFlow.ipynb

**Expected behavior**

export pairs as a dataframe

**Screenshots**

NameError                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 w.export_pairs()

File site-packages\pyjedai\workflow.py:195, in PYJEDAIWorkFlow.export_pairs(self)
    189 def export_pairs(self) -> pd.DataFrame:
    190     """Export pairs to file.
    191 
    192     Returns:
    193         pd.DataFrame: pairs as a DataFrame
    194     """
--> 195     return write(self.final_pairs, self.data)

NameError: name 'write' is not defined

**Desktop (please complete the following information):**
 - WIN 11, Chrome, pyjedai 0.1.7

**Additional context**
in the past 'write' was in evaluation.py

**Comment by Nikoletos-K** [comment]
Thanks for the detailed report. It is fixed and will be updated in the next public release!
